package org.codehaus.cake.internal.codegen;

enum Operation {
    PUSH, LOAD, STORE, PUT_FIELD, PUT_STATIC, RETURN,INVOKE, INVOKE_STATIC, CAST, GET, GET_STATIC, THROW, UNBOX, INVOKE_SPECIAL, DUP, NEW_INSTANCE, NEW_ARRAY, POP;
}
